### ISSUE TITLE
Package for Windows x64

### ISSUE THREAD

**Issue by tredgdhesc** [wxMEdit/wxMEdit#116]
Would you package for Windows x64 native in future?

original text:
你好，請問下以後會不會出64位元版本?
謝謝

**Comment by hltj** [comment]
original title: 請問下以後會不會出64位元版本?

**Comment by hltj** [comment]
The coming release wxMEdit 3.2 will package for Windows x64 native.
谢谢你的建议，近期的 wxMEdit 会出原生 64 位版本。

**Comment by Neonking** [comment]
Hello @tredgdhesc ,
I just joined wxMEdit team, thank you for using it. I'm running windows 10 / cygwin64 so i will be able  to realize windows builds / packaging for releases. By package did you meant a .msi file instead of .exe?
regards,
Jerome

**Comment by tredgdhesc** [comment]
不一定要EXE或msi
免安裝的7z或ZIP壓縮檔我覺得就很好了

**Comment by pnvnd** [comment]
Just wondering if version 3.2 will be packaged for Windows (64-bit) soon?  Version 3.1 is nice, it's just a bit annoying to changing the encoding every time I open a file.  I'd love to get a compiled version 3.2 to force encoding.  Thanks again for an amazing editor!  I've tried to download the dependencies and compile this myself without success...

**Comment by hltj** [comment]
> Just wondering if version 3.2 will be packaged for Windows (64-bit) soon? Version 3.1 is nice, it's just a bit annoying to changing the encoding every time I open a file. I'd love to get a compiled version 3.2 to force encoding. Thanks again for an amazing editor! I've tried to download the dependencies and compile this myself without success...

If it's the issue that encodings not restored after a restart, it will be fixed in the coming released wxMEdit 3.2. ( #213 )

**Comment by hltj** [comment]
3.2RC is released. Already packed for Windows x64.
https://wxmedit.github.io/zh_CN/downloads.html#prerelease
http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-win64-bin.7z

This release is actually stable enough. While waiting for localization and packaging for each system, the formal 3.2 is expected to be released in two weeks.

**Comment by hltj** [comment]
wxMEdit 3.2 already packed for Windows x64.
https://wxmedit.github.io/downloads.html
http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win64-bin.7z
http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win64-bin.zip
