### ISSUE TITLE
Two historical bug inherits from MadEdit

### ISSUE THREAD

**Issue by kesdoputr** [wxMEdit/wxMEdit#165]
1. [x] #167 The height of Information Window in MadEdit/wxMEdit (built with wxMSW-2.8) always reduce
2. [x] It didn't work if shortcut of exiting MadEdit/wxMEdit (built with wxMSW-2.8) set to Esc key

---

01.**InfoWindowHeight=设置的高度无法固定**
打开wxMEdit,按Ctrl+Shift+R叫出下头的**Fine/Replace in Files Results** 接着关闭wxMEdit
在wxmedit.cfg里头会多一行InfoWindowHeight=126的设置。
重覆上头的操作,设置会自动减少4变成InfoWindowHeight=122
一直重覆的话高度会一直以每次少4的状况减少到看不见的时候要自己拉高

02.**退出wxMEdit热键设置为Esc的时候没有作用**
想为File-Exit设定一个快捷来退出wxMEdit,设置成Esc的时候可以设置成功
但是按Esc不会有任何反应,设置成别的例出设成F1就可以顺利按F1退出wxMEdit

**Comment by hltj** [comment]
这两个问题都只存在于 Windows 版中，并且都是 wxWidgets 2.8 Windows 版本的 bug。
第一个问题暂时不解决，虽然 wxWidgets 3.0 不存在这个问题，但是 3.0 有一些其他问题，Windows 版暂时不会默认升到 3.0。

第二个问题会在 3.2 中修正，参见 #167 。

**Comment by hltj** [comment]
Original title: 从Madedit时就存在的两个小bug

**Comment by hltj** [comment]
Fixed as all wxMEdit 3.2 packages were packaged with wxWidgets 3.0.4 or later, wxMEdit 3.2 doesn't have the problem.
---
已修复，因 wxMEdit 3.2 所有包都是基于 wxWidgets 3.0.4 及后续版本的，wxMEdit 3.2 不存在该问题。
