### ISSUE TITLE
Stop compressing with 7z

### ISSUE THREAD

**Issue by danielson317** [wxMEdit/wxMEdit#186]
7z is nagware and carries lots of virus, ransomware, and other pup software's with it to install. please consider using a regular zip format instead.

**Comment by danielson317** [comment]
I was looking for a good hex editor and must refuse to use this one as I refuse to install the corrupt 7z zip applications.

**Comment by hltj** [comment]
I had never heard that 7-zip is such a malicious software. And I had never seen the evidence that the [official 7-zip](https://www.7-zip.org/) is malware. If you had ever used the unofficial 7-zip that was malware, please switch to the official one.

I can add zip archive as an alternative for the coming release (3.2), and it will be large than the 7-zip one. But I won’t stop providing the 7-zip archive rashly.

**Comment by hltj** [comment]
@danielson317 

3.2RC is released. With the alternative zip archives provided.
https://wxmedit.github.io/downloads.html#prerelease
http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-win64-bin.zipfor x64 Windows 7 or later
http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-win32-bin.zip for x86 Windows 7 or later
http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-win32-bin-xp.zip for Windows Xp/Vistar

This release is actually stable enough. While waiting for localization and packaging for each system, the formal 3.2 is expected to be released in two weeks.

**Comment by hltj** [comment]
3.2 is released. With the alternative zip archives provided for Win32/Win64.

| Operating System | Architecture | Package |
| ---------------- | ------------ | ------- |
| Windows 7 or later / Wine | amd64 | [wxMEdit-3.2-win64-bin.7z](http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win64-bin.7z) 12.8 MiB<br>[wxMEdit-3.2-win64-bin.zip](http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win64-bin.zip) 20.7 MiB |
| Windows XP or later / Wine | i386 | [wxMEdit-3.2-win32-bin.7z](https://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win32-bin.7z) 11.6 MiB<br>[wxMEdit-3.2-win32-bin.zip](https://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win32-bin.zip) 18.7 MiB |
| ReactOS | i386/amd64 | [wxMEdit-3.2-win32-bin-ros.7z](http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win32-bin-ros.7z) 9.64 MiB<br>[wxMEdit-3.2-win32-bin-ros.zip](http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win32-bin-ros.zip) 15.7 MiB |
