### ISSUE TITLE
Mint19 - Dependency not satisfiable libicu55 (>=55.1-1) Error

### ISSUE THREAD

**Issue by OneArb** [wxMEdit/wxMEdit#188]
Installing wxmedit_3.1-1_amd64-wx3-icu55.deb where libicu60 is available.

Thanks

**Comment by ituitis-cakici16** [comment]
I got the same problem

**Comment by VinnyVynce** [comment]
You could give a shot at my AppImage of wxMEdit, I need some more feedback to know if it works properly across every linux distributions. @OneArb @ituitis-cakici16 
https://github.com/VinnyVynce/wxMEdit.AppImage

**Comment by OneArb** [comment]
According to readme:

## Getting started
Look in releases, install the appimage then:

Can you please provide a link to download the AppImage?

**Comment by VinnyVynce** [comment]
> According to readme:
> ## Getting started
> 
> Look in releases, install the appimage then:
> 
> Can you please provide a link to download the AppImage?

https://github.com/VinnyVynce/wxMEdit.AppImage/releases

**Comment by procpay** [comment]
AppImage work ok,  you can also use this, the result will be the same 
Libicu55 is currently supported until Ubuntu 16.04 Xenial, but it is compatible with 18.04 Bionic.
Add the following repository and install the package
    sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
    sudo apt-get update
    sudo apt-get install libicu55

But I have a different problem: Cyrillic characters are not entered from the keyboard (I press the buttons and nothing is displayed), but the files with the Cyrillic symbols open and display the characters normally,  do нщг know how to fix it?

**Comment by OneArb** [comment]
I was able to load and use on Mint Linux.

Thanks

**Comment by sonichy** [comment]
Also has no libicu55, but has libicu57, libicu60 installed.

**Comment by hltj** [comment]
Sorry for reply so late.
It's been a long time. It should be Mint 21 for now, and [wxmedit_3.2_amd64-icu70.deb](http://downloads.sourceforge.net/project/wxmedit/3.2/wxmedit_3.2_amd64-icu70.deb) can be used.
