### ISSUE TITLE
Help with building on Debian 10 (Buster)?

### ISSUE THREAD

**Issue by Dwedit** [wxMEdit/wxMEdit#190]
I'm trying to run wxMEdit on a Debian Buster-based Linux Distro, in this case, MX Linux.
The package for Jessie is incompatible, since it wants to use `libicu52`, and Buster has `libicu63`.
So I'm trying to build it myself, and I'm running into problems.

First, `icu-config` was deprecated, and needs to be replaced with `pkg-config`.  One such replacement command I found by Googling was `"pkg-config --libs icu-uc icu-io icu-i18n"`, so I changed a line in configure.ac:

`ICUCONFIG=icu-config`
changed to
`ICUCONFIG="pkg-config --libs icu-uc icu-io icu-i18n"`

There's no guide for how to build the program, but I've gotten this far:

Install automake, gettext, libgtk2.0-dev, libglib2-dev, libwxgtk3.0-dev, libcurl4-openssl-dev, and probably others

Run these commands:
```
aclocal
automake --add-missing
automake
autoconf
./configure
```
I see some suspicious output when running ./configure:
```
checking for curl... yes
Unknown option --cppflags
Unknown option --ldflags
```
When I run make, I get a bunch of compiler errors like `"undefined reference to icu_63::UnicodeString::toLower"`, and it doesn't finish building.

Any help?

**Comment by VinnyVynce** [comment]
Hi, I had a lot of issues with building the app under PopOS 19.10. I ended up building it in a virtualized Ubuntu 16.04 and making a AppImage out of it.
https://github.com/VinnyVynce/wxMEdit.AppImage
I would love some more feedback

**Comment by fengjl026** [comment]
i build from debian10.3 
modify configure.ac:

gtk+-2.0  >= 2.6.0  to gtk+-3.0

**Comment by nerijus** [comment]
Please provide diffs, not the whole files.

**Comment by hltj** [comment]
Sorry for reply so late.
It's fixed in the latest code.

**Comment by yangu-hury** [comment]
Why doesn't make a portable Linux package.

**Comment by hltj** [comment]
A flatpak package may be available at a later date, but there are still many things to learn.

> Why doesn't make a portable Linux package.
