### ISSUE TITLE
Add appimage or flatpak as a download option for linux systems

### ISSUE THREAD

**Issue by VinnyVynce** [wxMEdit/wxMEdit#192]
Hi!
First off thanks for all the hard work that went through wxmedit, it's always my hex editor of choice however I think the installation process is always a mess. I think some work needs to be done with how easy it is to get access to the software. I think a flatpak package or an appimage should be added so the software is available regardless of the linux distribution. 
For example right now it's getting increasingly harder to build the application from source on 18.04 or higher. ICU dosen't offer what you need to actually build the app anymore and almost all modern package managers dosen't have wxWidgets, which means it needs to be built from source. Appimage or Flatpak with shared libraries could fix the issue.
Thanks!

**Comment by VinnyVynce** [comment]
I decided to make my own AppImage of wxMEdit. I would be glad if you could add my repository as a new download option for AppImage. Thanks!
https://github.com/VinnyVynce/wxMEdit.AppImage

**Comment by hltj** [comment]
Thank you so much.
I'd love to add it to the download list.
