### ISSUE TITLE
Cyrillic characters are not entered from the keyboard but opens files normaly

### ISSUE THREAD

**Issue by procpay** [wxMEdit/wxMEdit#195]
I have a different problem: Cyrillic characters are not entered from the keyboard (I press the buttons and nothing is displayed), but the files with the Cyrillic symbols open and display the characters normally, do you know how to fix it?   (Linux Mint 19)

**Comment by hltj** [comment]
wxMEdit 3.2 had fixed lots of character inputing relative issues, could you try the new release to see if it's fixed?
https://wxmedit.github.io/downloads.html

**Comment by procpay** [comment]
Yes! I downloaded the program two days ago, compiled from source. Now everything is great! I'm glad that the program continues to be updated

**Comment by hltj** [comment]
> Yes! I downloaded the program two days ago, compiled from source. Now everything is great! I'm glad that the program continues to be updated

Thanks for your feedback and support.
