### ISSUE TITLE
About force ANSI encoding

### ISSUE THREAD

**Issue by william19941994** [wxMEdit/wxMEdit#197]
I only using this tools to edit binary file.
But sometimes it auto check the encoding as non-ANSI.
I want to have a options to disable encoding guess.

**Comment by hltj** [comment]
You can check the following option in 'Options' dialog:

![gh_197_reply](https://user-images.githubusercontent.com/3896345/234654854-fef176b7-906b-471b-9d33-f9f77115ee6b.png)
