### ISSUE TITLE
An easy way to install under Ubunto Linux

### ISSUE THREAD

**Issue by beterhans** [wxMEdit/wxMEdit#198]
I don't know much about linux Develop but I figured out how you can install it under linux

Here is my example under Ubuntu 16.04
sudo apt install libcurl3-nss libwxbase3.0* libwxgtk3.0* libboost-all-dev

download the deb from
https://wxmedit.github.io/

sudo dpkg -i wxmedit_3.1-1_i386-wx3-icu55.deb
(you can't install the deb 1st or else your OS will be in a mess.)

**Comment by pnvnd** [comment]
On Ubuntu 20.04 and I had to also install `libicu55`:
```
sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
sudo apt-get update
sudo apt-get install libicu55
```
However, I'm having trouble with `libwxgtk3.0-0v5` not installing, even after adding repositories from `https://wiki.codelite.org/pmwiki.php/Main/WxWidgets30Binaries#toc2`.  Any ideas on how to get this working on newer versions of Ubuntu?

**Comment by hltj** [comment]
Sorry for reply so late.
It's been a long time. It should be Ubuntu 20.04/22.04/22.10/23.04 for now, these package can be used:
| Operating System | Architecture | Package |
| ---------------- | ------------ | ------- |
| Debian 12 / Ubuntu 23.04 | amd64 | [wxmedit_3.2_amd64-icu72.deb](http://downloads.sourceforge.net/project/wxmedit/3.2/wxmedit_3.2_amd64-icu72.deb) (1.18 MiB) |
| Ubuntu 22.10 / deepin v23 | amd64 | [wxmedit_3.2_amd64-icu71.deb](http://downloads.sourceforge.net/project/wxmedit/3.2/wxmedit_3.2_amd64-icu71.deb) (1.17 MiB) |
| Ubuntu 22.10 / deepin v23 | riscv64 | [wxmedit_3.2_riscv64-icu71.deb](http://downloads.sourceforge.net/project/wxmedit/3.2/wxmedit_3.2_riscv64-icu71.deb) (1.11 MiB) |
| Ubuntu 22.04 / Linux Mint 21 | amd64 | [wxmedit_3.2_amd64-icu70.deb](http://downloads.sourceforge.net/project/wxmedit/3.2/wxmedit_3.2_amd64-icu70.deb) (1.20 MiB) |
|Ubuntu 20.04 / openKylin 1.0 | amd64 | [wxmedit_3.2_amd64-icu66.deb](http://downloads.sourceforge.net/project/wxmedit/3.2/wxmedit_3.2_amd64-icu66.deb) (1.06 MiB) |

You can avoid manual installation dependencies by `sudo apt install path/to/wxmedit-package.deb` (replace `path/to/wxmedit-package.deb` to the real path).
