### ISSUE TITLE
How can I work wxMEdit on MacOS?

### ISSUE THREAD

**Issue by vladimirsimichorovich** [wxMEdit/wxMEdit#200]
I was looking for a cross-platform text editor in which regular expressions work and have found wxMEdit potentially useful.  I have a question about how it can be started on Mac OS (10.14).  I extracted wxMEdit-3.1_OSXFIX.tar.gz and got a folder of various files, but cannot identify which one is the main application.  On Windows I had no problem locating the .exe file, but the decompressed fragments look very much unlike Mac library parts.
Vladimir Simichorovich

**Comment by iMonZ** [comment]
> I was looking for a cross-platform text editor in which regular expressions work and have found wxMEdit potentially useful. I have a question about how it can be started on Mac OS (10.14). I extracted wxMEdit-3.1_OSXFIX.tar.gz and got a folder of various files, but cannot identify which one is the main application. On Windows I had no problem locating the .exe file, but the decompressed fragments look very much unlike Mac library parts.
> Vladimir Simichorovich

You need to execute the executable: "wxMEdit" in your terminal.
Just open the folder in the terminal and type: "./wxMEdit"

**Comment by hltj** [comment]
Sorry, wxMEdit did not provide binary packages for macOS.
You can download the source code and build it yourself.
Here is the building steps: https://github.com/wxMEdit/wxMEdit/issues/57#issuecomment-31417588 .
