### ISSUE TITLE
font always  rest to  "Courier New"  when next  launch wxMEdit

### ISSUE THREAD

**Issue by tablecell** [wxMEdit/wxMEdit#206]
version 3.1

view/set font to  "Open Sans"  
but  when next   launch wxMEdit   font reset to   "Courier New"

**Comment by sonichy** [comment]
Mine can remember font family, but can not remember font size.
Win7, 3.1

**Comment by hltj** [comment]
Hi @tablecell @sonichy ,

The 3.2RC has fixed this issue, these packages were packed yesterday (also fixed #215 ).
Of course, the formal  3.2 will be released soon. If you don’t mind upgrading again in a few days, you can try:

| Operating System | Architecture | Package |
| ---------------- | ------------ | ------- |
| Windows 7, 8, 10, 11 | amd64 | [wxMEdit-3.1.0.90-2-win64-bin.7z](http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-2-win64-bin.7z)<br>[wxMEdit-3.1.0.90-2-win64-bin.zip](http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-2-win64-bin.zip) |
| Windows 7, 8, 10, 11 | i386 | [wxMEdit-3.1.0.90-2-win32-bin.7z](http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-2-win32-bin.7z)<br>[wxMEdit-3.1.0.90-2-win32-bin.zip](http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-2-win32-bin.zip) |
| Windows Xp, Vista / ReactOS | i386/amd64 | [wxMEdit-3.1.0.90-2-win32-bin-xp.7z](http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-2-win32-bin-xp.7z)<br>[wxMEdit-3.1.0.90-2-win32-bin-xp.zip](http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-2-win32-bin-xp.zip) |
