### ISSUE TITLE
Moving to wxwidgets 3.2

### ISSUE THREAD

**Issue by petronny** [wxMEdit/wxMEdit#208]
Some distributions (such as Archlinux) has dropped the gtk2 version of wxwidgets (aka. wxgtk2).

Please move to wxwidgets-gtk3.

**Comment by hltj** [comment]
Yes.
The latest code already supports configuring with wxWidgets3-gtk3, and the next release will be coming soon.

**Comment by hltj** [comment]
Arch Linux, Ubuntu 23.04/Debian 12, FreeBSD 12/13/14 had already switched to wxWidgets 3.2 with GTK+ 3.
