### ISSUE TITLE
Installation Dependency Problem for wxmedit_3.1-1_amd64-wx3-icu55.deb

### ISSUE THREAD

**Issue by ipsmile** [wxMEdit/wxMEdit#209]
Linux Mint 20.3

Tried to install wxmedit_3.1-1_amd64-wx3-icu55.deb and received error messages:
Error: Dependency is not satisfiable: libwxgtk3.0-0v5 (>= 3.02+dfsg)

However, on my system libwxgtk3.0-gtk3-0v5 (3.0.4+dfsg-15build1) has been installed. 

Do I need libwxgtk3.0-gtk3-dev? 

How do I get around this error to complete the installation?

Thanks,

**Comment by hltj** [comment]
You can use http://downloads.sourceforge.net/project/wxmedit/3.2/wxmedit_3.2_amd64-icu66.deb .
And you can avoid manual installation dependencies by `sudo apt install path/to/wxmedit-package.deb` (replace `path/to/wxmedit-package.deb` to the real path).
