### ISSUE TITLE
No default encoding in the configuration 

### ISSUE THREAD

**Issue by flightbird** [wxMEdit/wxMEdit#212]
From the [Tools] -> [Option] -> [General], there is only one setting: "Use this encoding to create new file or when wxMEdit cannot determine the encoding of old file".  And this setting is not effective when opening file.
There is no default encoding in the configuration.

**Comment by hltj** [comment]
It's not like you said.

The default encoding in the configuration file is 'DefaultEncoding'. If it's empty string means that the default encoding is just the system default encoding.

And the default encoding often won't take effect when opening an existing file, but when creating a new file.
It will be used for existing file only when cannot determine the encoding. e.g. an empty file, a file only contains ASCIIs, etc.
