### ISSUE TITLE
暗黑模式能否加一个

### ISSUE THREAD

**Issue by snoopytl** [wxMEdit/wxMEdit#218]
大佬，能否加个暗黑模式，白色太亮了

**Comment by hltj** [comment]
窗口菜单这些会跟随环境主题变化。
语法高亮配置可以加载 Dark 或者 DarkBlue。

这个是 Linux XFCE 暗色主题的效果：

![dark_xfce1](https://github.com/wxMEdit/wxMEdit/assets/3896345/c971d0b5-4b36-4927-8f05-27ec40bc0a50)

**Comment by hltj** [comment]
original title: 暗黑模式能否加一个
