### ISSUE TITLE
想请问下，ubuntu 18.04 使用哪个版本

### ISSUE THREAD

**Issue by DaBaiTuu** [wxMEdit/wxMEdit#228]
你好，由于主页链接上，只看到了最低ubuntu20.04 给出的下载链接，所以想请问下 ubuntu18.04 应该怎么下载

**Comment by hltj** [comment]
Ubuntu 18.04  已经过了5年的支持周期，因此没有为其打包。建议升级到新版本，不要再使用不受支持的系统。
如果有特殊原因不得不使用旧版，可以考虑自行编译。

**Comment by DaBaiTuu** [comment]
> Ubuntu 18.04 已经过了5年的支持周期，因此没有为其打包。建议升级到新版本，不要再使用不受支持的系统。 如果有特殊原因不得不使用旧版，可以考虑自行编译。

确实需要使用18.04 因为工作环境，但是本人小白，可否指点下应如何自行编译，谢谢

**Comment by hltj** [comment]
> > Ubuntu 18.04 已经过了5年的支持周期，因此没有为其打包。建议升级到新版本，不要再使用不受支持的系统。 如果有特殊原因不得不使用旧版，可以考虑自行编译。
> 
> 确实需要使用18.04 因为工作环境，但是本人小白，可否指点下应如何自行编译，谢谢

```
apt install build-essential curl libgtk-3-dev libwxgtk3.0-gtk3-dev libboost-dev libicu-dev libcurl4-gnutls-dev
curl -LO https://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2.tar.gz
tar xf wxMEdit-3.2.tar.gz
cd wxMEdit-3.2
make wxmedit
sudo make install
```

**Comment by DaBaiTuu** [comment]
> > > Ubuntu 18.04 已经过了5年的支持周期，因此没有为其打包。建议升级到新版本，不要再使用不受支持的系统。 如果有特殊原因不得不使用旧版，可以考虑自行编译。
> > 
> > 
> > 确实需要使用18.04 因为工作环境，但是本人小白，可否指点下应如何自行编译，谢谢
> 
> ```
> sudo apt install build-essential curl libgtk-3-dev libwxgtk3.0-gtk3-dev libboost-dev libicu-dev libcurl4-gnutls-dev
> curl -LO https://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2.tar.gz
> tar xf wxMEdit-3.2.tar.gz
> cd wxMEdit-3.2
> make wxmedit
> sudo make install
> ```

打扰了，首先是第二步的下载由于命令行下载不成功我就直接去网址下载的，但是网址依旧不弹出下载链接，我就点击download problem 换了个能下载的，然后第四步出现如下问题，担心下载错误附上图像及描述：
![Screenshot from 2023-12-17 20-53-14](https://github.com/wxMEdit/wxMEdit/assets/120782756/6c65dca4-f7ac-4c46-83bb-bf787e701435)
述：
(make: *** No rule to make target 'wxmedit'.  Stop.) 
不胜感谢

**Comment by hltj** [comment]
> 打扰了，首先是第二步的下载由于命令行下载不成功我就直接去网址下载的，但是网址依旧不弹出下载链接，我就点击download problem 换了个能下载的，然后第四步出现如下问题，担心下载错误附上图像及描述：
> 
> Excuse me, Firstly the 2nd step, since the command line download failed, I went directly to the website to download, but the website still did not pop up the download link, so I clicked download problem and changed to a downloadable one. And then the 4th step, the following problem occurred. I'm worried about the download archive. Attached image and description:
> 
> ![Screenshot from 2023-12-17 20-53-14](https://private-user-images.githubusercontent.com/120782756/291063389-6c65dca4-f7ac-4c46-83bb-bf787e701435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzUxMTEsIm5iZiI6MTcwMjg3NDgxMSwicGF0aCI6Ii8xMjA3ODI3NTYvMjkxMDYzMzg5LTZjNjVkY2E0LWY3YWMtNGM0Ni04M2JiLWJmNzg3ZTcwMTQzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNDQ2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGFmNjIzY2EyNDA5NWNiOWE0MjFiNDhiN2E1MTBiZjU3MzM3YTA4ZmEwMTVmNzJkOWVhM2RiYzA5Y2ZhM2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WBfKgH14UFJiTSff_bZVLoN9SakuQPIGYoyzFnC6oZs)
> 
> (make: *** No rule to make target 'wxmedit'. Stop.)

我的错，应该不是下载错误。我之前的命令漏掉了：在 `make wxmedit` 之前需要执行 `touch aclocal.m4 configure Makefile.in config.h.in` 与 `./configure`。

It's my fault. It's probably not a download error. My previous commands missed: `touch aclocal.m4 configure Makefile.in config.h.in` and `./configure` need to be executed before `make wxmedit`.

**Comment by DaBaiTuu** [comment]
> > 打扰了，首先是第二步的下载由于命令行下载不成功我就直接去网址下载的，但是网址依旧不弹出下载链接，我就点击download problem 换了个能下载的，然后第四步出现如下问题，担心下载错误附上图像及描述：
> > Excuse me, Firstly the 2nd step, since the command line download failed, I went directly to the website to download, but the website still did not pop up the download link, so I clicked download problem and changed to a downloadable one. And then the 4th step, the following problem occurred. I'm worried about the download archive. Attached image and description:
> > ![Screenshot from 2023-12-17 20-53-14](https://private-user-images.githubusercontent.com/120782756/291063389-6c65dca4-f7ac-4c46-83bb-bf787e701435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzUxMTEsIm5iZiI6MTcwMjg3NDgxMSwicGF0aCI6Ii8xMjA3ODI3NTYvMjkxMDYzMzg5LTZjNjVkY2E0LWY3YWMtNGM0Ni04M2JiLWJmNzg3ZTcwMTQzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNDQ2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGFmNjIzY2EyNDA5NWNiOWE0MjFiNDhiN2E1MTBiZjU3MzM3YTA4ZmEwMTVmNzJkOWVhM2RiYzA5Y2ZhM2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WBfKgH14UFJiTSff_bZVLoN9SakuQPIGYoyzFnC6oZs)
> > (make: *** No rule to make target 'wxmedit'. Stop.)
> 
> 我的错，应该不是下载错误。我之前的命令漏掉了：在 `make wxmedit` 之前需要执行 `touch aclocal.m4 configure Makefile.in config.h.in` 与 `./configure`。（命令已更新）
> 
> It's my fault. It's probably not a download error. My previous commands missed: `touch aclocal.m4 configure Makefile.in config.h.in` and `./configure` need to be executed before `make wxmedit`. (the commands updated)

多谢 ， 已安装成功
