### ISSUE TITLE
port to wxWidgets 3.0

### ISSUE THREAD

**Issue by nerijus** [wxMEdit/wxMEdit#43]

**Comment by CandyFace** [comment]
Is this something you intend to fix soon? I have been trying to compile wxMEdit on OS X 10.10 for quite some time now, without success. I am using wxWidgets 3.0.2 and are unfortunately not able to use 2.8.0

**Comment by hltj** [comment]
I will begin to deal with it these days. While I not sure that it can be build under OS X soon.

**Comment by Neonking** [comment]
sounds like 3.2 release will close the issue :)
