### ISSUE TITLE
Bugged mouse control when activate a tab with the file changed external (wxGTK <= 3.0.2)

### ISSUE THREAD

**Issue by vehona** [wxMEdit/wxMEdit#89]
It was happening as much as I remember using wxMEdit but until now I was thinking that probably there was something wrong with my system and not the application. But after getting same issue on my second systems too, it's likely to be bug.
If you have several documents opened in wxMEdit and try to modify one of them which is kept in inactive tab of wxMEdit and make its tab active, it will cause broken mouse control for some time, like not being able to press buttons with mouse or left-click to specific part of the document (keyboard controls work fine). It can be fixed after ~5 second of clicking left and right buttons on the mouse.
This issue doesn't happen if the modified document was in active tab. It happens for Linux systems (not sure about other ones).

**Comment by hltj** [comment]
Confirmed. It happens for UNIX like OSes.

**Comment by hltj** [comment]
original title: Bugged mouse control after external file changes

**Comment by MrColdbird** [comment]
Can confirm this behavior, also affected.

**Comment by vehona** [comment]
Any news on possible fixes?

**Comment by hltj** [comment]
The may be a bug of wxGTK-2.8. It does not have this problem if built against wxGTK-3.0.
While the exact cause was not identified.

**Comment by Neonking** [comment]
Well, another issue that 3.2 release should close with the almost complete Wxwidgets-3.0 port 😄

**Comment by hltj** [comment]
Fixed as all wxMEdit 3.2 packages were packaged with wxWidgets 3.0.4 or later.
